# Generated by Django 5.2.12 on 2026-03-20 16:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Band điểm')),
                ('order_index', models.IntegerField(verbose_name='Thứ tự lộ trình')),
            ],
            options={
                'verbose_name': 'Band điểm',
                'verbose_name_plural': '2.3 Band điểm',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên cơ sở')),
                ('address', models.TextField(verbose_name='Địa chỉ')),
            ],
            options={
                'verbose_name': 'Cơ sở',
                'verbose_name_plural': '2.1 Cơ sở',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('dob', models.DateField(null=True, verbose_name='Ngày sinh')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang học'), ('INACTIVE', 'Đã nghỉ')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('parent_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Phụ huynh')),
                ('parent_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT Phụ huynh')),
            ],
            options={
                'verbose_name': 'Học viên',
                'verbose_name_plural': '3.1 Danh sách Học viên',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'System Admin'), ('MANAGER', 'Quản lý'), ('STAFF', 'Giáo vụ'), ('TEACHER', 'Giáo viên')], default='STAFF', max_length=20, verbose_name='Vai trò')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số điện thoại')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Tài khoản',
                'verbose_name_plural': '1. Quản lý Tài khoản',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên khóa học')),
                ('start_date', models.DateField(verbose_name='Ngày khai giảng dự kiến')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.branch', verbose_name='Thuộc Cơ sở')),
            ],
            options={
                'verbose_name': 'Khóa học',
                'verbose_name_plural': '2.2 Khóa học',
            },
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Mã Lớp học')),
                ('status', models.CharField(choices=[('ACTIVE', 'Đang mở'), ('INACTIVE', 'Đóng')], default='ACTIVE', max_length=20, verbose_name='Trạng thái')),
                ('band', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='api.band', verbose_name='Thuộc Band')),
                ('teachers', models.ManyToManyField(limit_choices_to={'role': 'TEACHER'}, related_name='class_groups', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên phụ trách')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='api.course', verbose_name='Thuộc Khóa')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_classes', to='api.student', verbose_name='Học viên của lớp')),
            ],
            options={
                'verbose_name': 'Lớp học & Xếp lớp',
                'verbose_name_plural': '2.4 Lớp học & Xếp lớp',
            },
        ),
        migrations.CreateModel(
            name='StudentTuition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, verbose_name='Tổng tiền phải đóng')),
                ('installments_planned', models.IntegerField(default=1, verbose_name='Số đợt chia đóng')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='api.student', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Hồ sơ Học phí',
                'verbose_name_plural': '3.3 Hồ sơ Học phí (Đăng ký gói)',
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.IntegerField(verbose_name='Đợt thanh toán số')),
                ('amount_due', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền cần đóng')),
                ('status', models.CharField(choices=[('PENDING', 'Chưa đóng'), ('PAID', 'Đã đóng')], default='PENDING', max_length=20, verbose_name='Trạng thái')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Ngày thu')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người thu')),
                ('student_tuition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.studenttuition', verbose_name='Thuộc Hồ sơ học phí')),
            ],
            options={
                'verbose_name': 'Phiếu thu',
                'verbose_name_plural': '3.4 Lịch sử Phiếu thu',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('CHUYEN_LOP', 'Chuyển lớp'), ('XIN_NGUNG_HOC', 'Xin ngừng học'), ('XIN_PHAN_HOI', 'Xin phản hồi về học viên'), ('BAO_LUU', 'Bảo lưu'), ('XIN_HOC_LAI', 'Xin học lại'), ('KHAC', 'Khác')], max_length=50, verbose_name='Loại công việc')),
                ('status', models.CharField(choices=[('CHO_GIAO_VIEN_DUYET', 'Đang chờ giáo viên duyệt'), ('CHO_QUAN_LY_DUYET', 'Đang chờ quản lý duyệt'), ('CAN_THEM_THONG_TIN', 'Cần thêm thông tin'), ('GIAO_VIEN_DUYET', 'Giáo viên đã duyệt'), ('QUAN_LY_DUYET', 'Quản lý đã duyệt'), ('HOAN_TAT', 'Hoàn tất'), ('TU_CHOI', 'Từ chối')], default='CHO_GIAO_VIEN_DUYET', max_length=20, verbose_name='Trạng thái')),
                ('teacher_rejection_reason', models.TextField(blank=True, null=True, verbose_name='Lý do GV từ chối')),
                ('manager_rejection_reason', models.TextField(blank=True, null=True, verbose_name='Lý do QL từ chối')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối')),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý hiện tại')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Task (Công việc)',
                'verbose_name_plural': '4.1 Quản lý Task',
            },
        ),
        migrations.CreateModel(
            name='TuitionPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên Gói học phí')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền (VNĐ)')),
                ('package_type', models.CharField(choices=[('SINGLE', 'Lẻ từng Band'), ('ROADMAP', 'Lộ trình nhiều Band')], max_length=20, verbose_name='Loại gói')),
                ('bands_included', models.ManyToManyField(related_name='tuition_packages', to='api.band', verbose_name='Bao gồm các Band')),
            ],
            options={
                'verbose_name': 'Gói Học phí',
                'verbose_name_plural': '3.2 Gói Học phí',
            },
        ),
        migrations.AddField(
            model_name='studenttuition',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_tuitions', to='api.tuitionpackage', verbose_name='Gói đã mua'),
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listening_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm Nghe')),
                ('listening_fb', models.TextField(blank=True, null=True, verbose_name='Nhận xét Nghe')),
                ('speaking_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm Nói')),
                ('speaking_fb', models.TextField(blank=True, null=True, verbose_name='Nhận xét Nói')),
                ('reading_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm Đọc')),
                ('reading_fb', models.TextField(blank=True, null=True, verbose_name='Nhận xét Đọc')),
                ('writing_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm Viết')),
                ('writing_fb', models.TextField(blank=True, null=True, verbose_name='Nhận xét Viết')),
                ('is_finalized', models.BooleanField(default=False, verbose_name='Đã chốt điểm gửi Giáo vụ')),
                ('class_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.classgroup', verbose_name='Lớp học')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.student', verbose_name='Học viên')),
            ],
            options={
                'verbose_name': 'Bảng điểm 4 Kỹ năng',
                'verbose_name_plural': '4.2 Bảng điểm 4 Kỹ năng',
                'unique_together': {('student', 'class_group')},
            },
        ),
    ]
