# Generated by Django 5.2.12 on 2026-03-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Học viên', 'verbose_name_plural': '3.1 Học viên'},
        ),
        migrations.AddField(
            model_name='studenttuition',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'Đang đóng'), ('COMPLETED', 'Đã hoàn thành')], default='IN_PROGRESS', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
