# Generated by Django 5.2.12 on 2026-03-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CHO_GIAO_VIEN_DUYET', 'Đang chờ giáo viên duyệt'), ('CHO_QUAN_LY_DUYET', 'Đang chờ quản lý duyệt'), ('CAN_THEM_THONG_TIN', 'Cần thêm thông tin'), ('GIAO_VIEN_DUYET', 'Giáo viên đã duyệt'), ('QUAN_LY_DUYET', 'Quản lý đã duyệt'), ('HOAN_TAT', 'Hoàn tất'), ('TU_CHOI', 'Từ chối')], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('CHUYEN_LOP', 'Chuyển lớp'), ('XIN_NGUNG_HOC', 'Xin ngừng học'), ('XIN_PHAN_HOI', 'Xin phản hồi về học viên'), ('BAO_LUU', 'Bảo lưu'), ('XIN_HOC_LAI', 'Xin học lại'), ('KHAC', 'Khác')], max_length=50),
        ),
    ]
