# Generated by Django 5.2.12 on 2026-03-20 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_parent_name_student_parent_phone_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'ordering': ['order_index'], 'verbose_name': 'Lớp học (Band)', 'verbose_name_plural': '2. Quản lý Lớp học (Band)'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Chi nhánh', 'verbose_name_plural': '2. Quản lý Chi nhánh'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Khóa học', 'verbose_name_plural': '2. Quản lý Khóa học'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Tài khoản', 'verbose_name_plural': '1. Quản lý Tài khoản'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='rejection_reason',
        ),
        migrations.AddField(
            model_name='task',
            name='manager_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='teacher_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên lớp học (Band)'),
        ),
        migrations.AlterField(
            model_name='band',
            name='order_index',
            field=models.IntegerField(verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.TextField(verbose_name='Địa chỉ'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=25, verbose_name='Tên chi nhánh'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang mở'), ('INACTIVE', 'Đóng')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.branch', verbose_name='Thuộc cơ sở'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên khóa học'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(verbose_name='Ngày khai giảng'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang học'), ('INACTIVE', 'Đã nghỉ')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'System Admin'), ('MANAGER', 'Quản lý'), ('STAFF', 'Giáo vụ'), ('TEACHER', 'Giáo viên')], default='STAFF', max_length=20, verbose_name='Vai trò'),
        ),
    ]
