# Generated by Django 5.2.12 on 2026-03-20 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_band_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'verbose_name': 'Band ', 'verbose_name_plural': '2.3 Band'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Chi nhánh', 'verbose_name_plural': '2.1 Chi nhánh'},
        ),
        migrations.AlterModelOptions(
            name='classgroup',
            options={'verbose_name': 'Lớp học', 'verbose_name_plural': '2.4 Lớp học'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Khóa học', 'verbose_name_plural': '2.2 Khóa học'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Xếp lớp', 'verbose_name_plural': '3.5 Quá trình Xếp lớp'},
        ),
        migrations.AlterModelOptions(
            name='graderecord',
            options={'verbose_name': 'Bảng điểm 4 Kỹ năng', 'verbose_name_plural': '4.2 Bảng điểm 4 Kỹ năng'},
        ),
        migrations.AlterModelOptions(
            name='paymentreceipt',
            options={'verbose_name': 'Phiếu thu', 'verbose_name_plural': '3.4 Lịch sử Phiếu thu'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Học viên', 'verbose_name_plural': '3.1 Danh sách Học viên'},
        ),
        migrations.AlterModelOptions(
            name='studenttuition',
            options={'verbose_name': 'Hồ sơ Học phí', 'verbose_name_plural': '3.3 Hồ sơ Học phí (Đăng ký gói)'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Task (Công việc)', 'verbose_name_plural': '4.1 Quản lý Task'},
        ),
        migrations.AlterModelOptions(
            name='tuitionpackage',
            options={'verbose_name': 'Gói Học phí', 'verbose_name_plural': '3.2 Gói Học phí'},
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='band',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_groups', to='api.band', verbose_name='Thuộc Band'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to='api.course', verbose_name='Thuộc Khóa'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Mã Lớp học'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang mở'), ('INACTIVE', 'Đóng')], default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='classgroup',
            name='teachers',
            field=models.ManyToManyField(limit_choices_to={'role': 'TEACHER'}, related_name='class_groups', to=settings.AUTH_USER_MODEL, verbose_name='Giáo viên phụ trách'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classgroup', verbose_name='Vào Lớp học'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='enroll_date',
            field=models.DateField(auto_now_add=True, verbose_name='Ngày xếp lớp'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student', verbose_name='Học viên'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='class_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.classgroup', verbose_name='Lớp học'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='listening_fb',
            field=models.TextField(blank=True, null=True, verbose_name='Nhận xét Nghe'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='listening_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm Nghe'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='reading_fb',
            field=models.TextField(blank=True, null=True, verbose_name='Nhận xét Đọc'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='reading_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm Đọc'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='speaking_fb',
            field=models.TextField(blank=True, null=True, verbose_name='Nhận xét Nói'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='speaking_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm Nói'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='api.student', verbose_name='Học viên'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='writing_fb',
            field=models.TextField(blank=True, null=True, verbose_name='Nhận xét Viết'),
        ),
        migrations.AlterField(
            model_name='graderecord',
            name='writing_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Điểm Viết'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='amount_paid',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền đã thu'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='paid_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày thu'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Người thu'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='student_tuition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.studenttuition', verbose_name='Thuộc Hồ sơ học phí'),
        ),
        migrations.AlterField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Họ và tên'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Phụ huynh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='SĐT Phụ huynh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Đang học'), ('INACTIVE', 'Đã nghỉ')], default='ACTIVE', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='studenttuition',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng ký'),
        ),
        migrations.AlterField(
            model_name='studenttuition',
            name='installments_planned',
            field=models.IntegerField(default=1, verbose_name='Số đợt chia đóng'),
        ),
        migrations.AlterField(
            model_name='studenttuition',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_tuitions', to='api.tuitionpackage', verbose_name='Gói đã mua'),
        ),
        migrations.AlterField(
            model_name='studenttuition',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tuitions', to='api.student', verbose_name='Học viên'),
        ),
        migrations.AlterField(
            model_name='studenttuition',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền phải đóng'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người xử lý hiện tại'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo'),
        ),
        migrations.AlterField(
            model_name='task',
            name='manager_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do QL từ chối'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('CHO_GIAO_VIEN_DUYET', 'Đang chờ giáo viên duyệt'), ('CHO_QUAN_LY_DUYET', 'Đang chờ quản lý duyệt'), ('CAN_THEM_THONG_TIN', 'Cần thêm thông tin'), ('GIAO_VIEN_DUYET', 'Giáo viên đã duyệt'), ('QUAN_LY_DUYET', 'Quản lý đã duyệt'), ('HOAN_TAT', 'Hoàn tất'), ('TU_CHOI', 'Từ chối')], default='CHO_GIAO_VIEN_DUYET', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('CHUYEN_LOP', 'Chuyển lớp'), ('XIN_NGUNG_HOC', 'Xin ngừng học'), ('XIN_PHAN_HOI', 'Xin phản hồi về học viên'), ('BAO_LUU', 'Bảo lưu'), ('XIN_HOC_LAI', 'Xin học lại'), ('KHAC', 'Khác')], max_length=50, verbose_name='Loại công việc'),
        ),
        migrations.AlterField(
            model_name='task',
            name='teacher_rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Lý do GV từ chối'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Cập nhật lần cuối'),
        ),
        migrations.AlterField(
            model_name='tuitionpackage',
            name='bands_included',
            field=models.ManyToManyField(related_name='tuition_packages', to='api.band', verbose_name='Bao gồm các Band'),
        ),
        migrations.AlterField(
            model_name='tuitionpackage',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên Gói học phí'),
        ),
        migrations.AlterField(
            model_name='tuitionpackage',
            name='package_type',
            field=models.CharField(choices=[('SINGLE', 'Lẻ từng Band'), ('ROADMAP', 'Lộ trình nhiều Band')], max_length=20, verbose_name='Loại gói'),
        ),
        migrations.AlterField(
            model_name='tuitionpackage',
            name='total_price',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Tổng tiền (VNĐ)'),
        ),
    ]
