# Generated by Django 5.2.12 on 2026-03-20 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_band_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='band',
            options={'verbose_name': 'Band điểm', 'verbose_name_plural': '2.3 Band điểm'},
        ),
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Cơ sở', 'verbose_name_plural': '2.1 Cơ sở đào tạo'},
        ),
        migrations.AlterModelOptions(
            name='classgroup',
            options={'verbose_name': 'Lớp học & Xếp lớp', 'verbose_name_plural': '2.4 Lớp học & Xếp lớp'},
        ),
        migrations.AddField(
            model_name='classgroup',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', to='api.student', verbose_name='Học viên của lớp'),
        ),
        migrations.AlterField(
            model_name='band',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên Band điểm'),
        ),
        migrations.AlterField(
            model_name='band',
            name='order_index',
            field=models.IntegerField(verbose_name='Thứ tự lộ trình'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tên cơ sở'),
        ),
        migrations.AlterField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.branch', verbose_name='Thuộc Cơ sở'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateField(verbose_name='Ngày khai giảng dự kiến'),
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
