# Generated by Django 5.2.12 on 2026-03-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_band_options_alter_branch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name': 'Cơ sở', 'verbose_name_plural': '2.1 Cơ sở'},
        ),
        migrations.AddField(
            model_name='student',
            name='dob',
            field=models.DateField(null=True, verbose_name='Ngày sinh'),
        ),
    ]
